# SPDX-License-Identifier: BUSL-1.1
#
# Copyright (C) 2023, Berachain Foundation. All rights reserved.
# Use of this software is govered by the Business Source License included
# in the LICENSE file of this repository and at www.mariadb.com/bsl11.
#
# ANY USE OF THE LICENSED WORK IN VIOLATION OF THIS LICENSE WILL AUTOMATICALLY
# TERMINATE YOUR RIGHTS UNDER THIS LICENSE FOR THE CURRENT AND ALL OTHER
# VERSIONS OF THE LICENSED WORK.
#
# THIS LICENSE DOES NOT GRANT YOU ANY RIGHT IN ANY TRADEMARK OR LOGO OF
# LICENSOR OR ITS AFFILIATES (PROVIDED THAT YOU MAY USE A TRADEMARK OR LOGO OF
# LICENSOR AS EXPRESSLY REQUIRED BY THIS LICENSE).
#
# TO THE EXTENT PERMITTED BY APPLICABLE LAW, THE LICENSED WORK IS PROVIDED ON
# AN “AS IS” BASIS. LICENSOR HEREBY DISCLAIMS ALL WARRANTIES AND CONDITIONS,
# EXPRESS OR IMPLIED, INCLUDING (WITHOUT LIMITATION) WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND
# TITLE.

version: "3.3"

services:
  node0:
    container_name: polard-node0
    image: "polard/seed:v0.0.0"
    ports:
      - "26656-26658:26656-26658"
      - "9090-9091:9090-9091"
    environment:
      - ID=0
      - CHAINID=berachain-localnet-666
      - DIALURL=http://polard-reth0:8551
      - JWTSECRETPATH=/root/ethgen/jwt.hex
    volumes:
      - type: bind
        source: ./temp/seed0
        target: /root
      - type: bind
        source: ./ethgen
        target: /root/ethgen
    networks:
      localnet:
        ipv4_address: 192.168.10.10

  reth0:
    container_name: polard-reth0
    image: ghcr.io/paradigmxyz/reth
    command: |
      node --http.api eth,net,txpool,rpc,web3 --chain /root/ethgen/genesis.json --http --authrpc.jwtsecret /root/ethgen/jwt.hex --http.port 8545 --authrpc.port 8551 --http.corsdomain "*" --authrpc.addr 192.168.10.11
    volumes:
      - type: bind
        source: ./ethgen
        target: /root/ethgen
    networks:
      localnet:
        ipv4_address: 192.168.10.11
    ports:
      - "8545:8545"
      - "8551:8551"

  node1:
    container_name: polard-node1
    image: "polard/seed:v0.0.0"
    ports:
      - "36656-36658:26656-26658"
      - "10090-10091:9090-9091"
    environment:
      - ID=1
      - CHAINID=berachain-localnet-666
      - DIALURL=http://polard-reth1:9551
      - JWTSECRETPATH=/root/ethgen/jwt.hex
    volumes:
      - type: bind
        source: ./temp/seed1
        target: /root
      - type: bind
        source: ./ethgen
        target: /root/ethgen
    networks:
      localnet:
        ipv4_address: 192.168.10.12

  reth1:
    container_name: polard-reth1
    image: ghcr.io/paradigmxyz/reth
    command: |
      node --http.api eth,net,txpool,rpc,web3 --chain /root/ethgen/genesis.json --http --authrpc.jwtsecret /root/ethgen/jwt.hex --http.port 9545 --authrpc.port 9551 --http.corsdomain "*" --authrpc.addr 192.168.10.13
    volumes:
      - type: bind
        source: ./ethgen
        target: /root/ethgen
    networks:
      localnet:
        ipv4_address: 192.168.10.13
    ports:
      - "9551:9951"

  node2:
    container_name: polard-node2
    image: "polard/seed:v0.0.0"
    ports:
      - "46656-46658:26656-26658"
      - "11090-11091:9090-9091"
    environment:
      - ID=2
      - CHAINID=berachain-localnet-666
      - DIALURL=http://polard-reth2:10551
      - JWTSECRETPATH=/root/ethgen/jwt.hex
    volumes:
      - type: bind
        source: ./temp/seed2
        target: /root
      - type: bind
        source: ./ethgen
        target: /root/ethgen
    networks:
      localnet:
        ipv4_address: 192.168.10.14

  reth2:
    container_name: polard-reth2
    image: ghcr.io/paradigmxyz/reth
    command: |
      node --http.api eth,net,txpool,rpc,web3 --chain /root/ethgen/genesis.json --http --authrpc.jwtsecret /root/ethgen/jwt.hex --http.port 10545 --authrpc.port 10551 --http.corsdomain "*" --authrpc.addr 192.168.10.15
    volumes:
      - type: bind
        source: ./ethgen
        target: /root/ethgen
    networks:
      localnet:
        ipv4_address: 192.168.10.15
    ports:
      - "10545:8545"
      - "10551:8551"

  node3:
    container_name: polard-node3
    image: "polard/seed:v0.0.0"
    ports:
      - "56665-56667:26656-26658"
      - "12096-12097:9090-9091"
    environment:
      - ID=3
      - CHAINID=berachain-localnet-666
      - DIALURL=http://polard-reth3:11551
      - JWTSECRETPATH=/root/ethgen/jwt.hex
    volumes:
      - type: bind
        source: ./temp/seed3
        target: /root
      - type: bind
        source: ./ethgen
        target: /root/ethgen
    networks:
      localnet:
        ipv4_address: 192.168.10.16

  reth3:
    container_name: polard-reth3
    image: ghcr.io/paradigmxyz/reth
    command: |
      node --http.api eth,net,txpool,rpc,web3 --chain /root/ethgen/genesis.json --http --authrpc.jwtsecret /root/ethgen/jwt.hex --http.port 11545 --authrpc.port 11551 --http.corsdomain "*" --authrpc.addr 192.168.10.17
    volumes:
      - type: bind
        source: ./ethgen
        target: /root/ethgen
    networks:
      localnet:
        ipv4_address: 192.168.10.17
    ports:
      - "11545:8545"
      - "11551:8551"

networks:
  localnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24

