dir: "{{.InterfaceDir}}/mocks"
mockname: "{{.InterfaceNameCamel}}"
filename: "{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
packages:
  github.com/itsdevbear/bolaris/cosmos/config:
    config:
      recursive: True
      with-expecter: true
      all: True
