coverage:
  status:
    project:
      default:
        target: 45%
    patch: off

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  show_carryforward_flags: true

ignore:
  - "**/*.pb.go"
  - "**/*.pb.gw.go"
  - "**/*.pulsar.go"
  - "**/*.abigen.go"
  - "**/*.rlpgen.go"
  - "**/*.mock.go"
  - "**/proto"
  - "**/build"
  - "**/cmd"
