# SPDX-License-Identifier: MIT
#
# Copyright (c) 2023 Berachain Foundation
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

version: "3.3"

services:
  node0:
    container_name: beacond-node0
    image: "beacond/seed:v0.0.0"
    ports:
      - "26656-26658:26656-26658"
      - "9090-9091:9090-9091"
    environment:
      - ID=0
      - CHAINID=berachain-localnet-666
      - DIALURL=http://beacond-reth0:8551
      - JWTSECRETPATH=/root/ethgen/jwt.hex
    volumes:
      - type: bind
        source: ./temp/seed0
        target: /root
      - type: bind
        source: ./ethgen
        target: /root/ethgen
    networks:
      localnet:
        ipv4_address: 192.168.10.10


  # Other nodes will use reth0 as their bootnode
  # enode://c58ccefeae4d769d0212d0e9d44aa0a5bc49765d472e758ce16fe9518acb74e576a522a783677ad370f3c3a4991f831a89e0dc02ac18667dd824eb5931d3fca5@192.168.10.11:30303
  reth0:
    container_name: beacond-reth0
    image: ghcr.io/paradigmxyz/reth
    command: >
      node --http.api eth,net,txpool,rpc,web3
      --chain /root/ethgen/genesis.json
      --http
      --authrpc.jwtsecret /root/ethgen/jwt.hex
      --http.addr 192.168.10.11
      --http.port 8545
      --authrpc.port 8551
      --http.corsdomain "*"
      --authrpc.addr 192.168.10.11
      --discovery.addr 192.168.10.11
      --discovery.port 30303
      --addr 192.168.10.11
      --port 30303
      --p2p-secret-key /root/ethgen/p2p-secret-0.key
      --builder.deadline 3
      --builder.max-tasks 24
    volumes:
      - type: bind
        source: ./ethgen
        target: /root/ethgen
    networks:
      localnet:
        ipv4_address: 192.168.10.11
    ports:
      - "8545:8545"
      - "8551:8551"
      - "30303:30303"

  node1:
    container_name: beacond-node1
    image: "beacond/seed:v0.0.0"
    ports:
      - "36656-36658:26656-26658"
      - "10090-10091:9090-9091"
    environment:
      - ID=1
      - CHAINID=berachain-localnet-666
      - DIALURL=http://beacond-reth1:9551
      - JWTSECRETPATH=/root/ethgen/jwt.hex
    volumes:
      - type: bind
        source: ./temp/seed1
        target: /root
      - type: bind
        source: ./ethgen
        target: /root/ethgen
    networks:
      localnet:
        ipv4_address: 192.168.10.12

  # enode://0b5632872cfca278b2a0403c9d691789a198f6950cd7bbee1b7aaa2f2afa55330a5daafe955a90f2ae510b40049d4b20bc1f0b0f4c7b017391664e9521692da3@192.168.10.13:40303
  reth1:
    container_name: beacond-reth1
    image: ghcr.io/paradigmxyz/reth
    command: >
      node --http.api eth,net,txpool,rpc,web3
      --chain /root/ethgen/genesis.json
      --http
      --authrpc.jwtsecret /root/ethgen/jwt.hex
      --http.addr 192.168.10.13
      --http.port 9545
      --authrpc.port 9551
      --http.corsdomain "*"
      --authrpc.addr 192.168.10.13
      --discovery.addr 192.168.10.13
      --discovery.port 40303
      --addr 192.168.10.13
      --port 40303
      --p2p-secret-key /root/ethgen/p2p-secret-1.key
      --bootnodes enode://c58ccefeae4d769d0212d0e9d44aa0a5bc49765d472e758ce16fe9518acb74e576a522a783677ad370f3c3a4991f831a89e0dc02ac18667dd824eb5931d3fca5@192.168.10.11:30303
      --builder.deadline 3
      --builder.max-tasks 24
    volumes:
      - type: bind
        source: ./ethgen
        target: /root/ethgen
    networks:
      localnet:
        ipv4_address: 192.168.10.13
    ports:
      - "9545:9545"
      - "9551:9551"
      - "40303:40303"

  node2:
    container_name: beacond-node2
    image: "beacond/seed:v0.0.0"
    ports:
      - "46656-46658:26656-26658"
      - "11090-11091:9090-9091"
    environment:
      - ID=2
      - CHAINID=berachain-localnet-666
      - DIALURL=http://beacond-reth2:10551
      - JWTSECRETPATH=/root/ethgen/jwt.hex
    volumes:
      - type: bind
        source: ./temp/seed2
        target: /root
      - type: bind
        source: ./ethgen
        target: /root/ethgen
    networks:
      localnet:
        ipv4_address: 192.168.10.14


  # enode://3d356b2c6425336a48f42a401081addaa5c1643c7bfb9df5e3792228383a4b14ad699ab13ecfedcaf60fcd6bd62c6149736e4e5e03635375215f0d770dc74c1f@192.168.10.15:50303
  reth2:
    container_name: beacond-reth2
    image: ghcr.io/paradigmxyz/reth
    command: >
      node --http.api eth,net,txpool,rpc,web3
      --chain /root/ethgen/genesis.json
      --http
      --http.port 10545
      --authrpc.port 10551
      --authrpc.jwtsecret /root/ethgen/jwt.hex
      --http.corsdomain "*"
      --http.addr 192.168.10.15
      --authrpc.addr 192.168.10.15
      --discovery.addr 192.168.10.15
      --discovery.port 50303
      --addr 192.168.10.15
      --port 50303
      --p2p-secret-key /root/ethgen/p2p-secret-2.key
      --bootnodes enode://c58ccefeae4d769d0212d0e9d44aa0a5bc49765d472e758ce16fe9518acb74e576a522a783677ad370f3c3a4991f831a89e0dc02ac18667dd824eb5931d3fca5@192.168.10.11:30303
      --builder.deadline 3
      --builder.max-tasks 24
    volumes:
      - type: bind
        source: ./ethgen
        target: /root/ethgen
    networks:
      localnet:
        ipv4_address: 192.168.10.15
    ports:
      - "10545:10545"
      - "10551:10551"
      - "50303:50303"


  node3:
    container_name: beacond-node3
    image: "beacond/seed:v0.0.0"
    ports:
      - "56665-56667:26656-26658"
      - "12096-12097:9090-9091"
    environment:
      - ID=3
      - CHAINID=berachain-localnet-666
      - DIALURL=http://192.168.10.17:11551
      - JWTSECRETPATH=/root/ethgen/jwt.hex
    volumes:
      - type: bind
        source: ./temp/seed3
        target: /root
      - type: bind
        source: ./ethgen
        target: /root/ethgen
    networks:
      localnet:
        ipv4_address: 192.168.10.16

  # enode://fef1c19f87dd4c1221538c380715d88f3de6809a86738546a7738bb36094365e9fed49fe30e0411217b3eacca120afa2bb0d5cd6e29643abd61b261585bb68b2@192.168.10.17:60303
  reth3:
    container_name: beacond-reth3
    # image: ethereum/client-go:stab
    # environment:
    #   - GETH_GRAPHQL_VHOSTS=*
    # command: > 
    #   --authrpc.vhosts *
    #   --http.api eth,net,txpool,rpc,web3
    #   --http
    #   --http.port 11545
    #   --http.addr 192.168.10.17
    #   --http.corsdomain *
    #   
    #  /root/ethgen/jwt.hex
    #   --authrpc.addr 192.168.10.17
    #   --authrpc.port 11551
    #   --datadir /root/ethgen/gethdatadir
    #   --bootnodes enode://c58ccefeae4d769d0212d0e9d44aa0a5bc49765d472e758ce16fe9518acb74e576a522a783677ad370f3c3a4991f831a89e0dc02ac18667dd824eb5931d3fca5@192.168.10.11:30303
    image: ghcr.io/paradigmxyz/reth
    command: >
      node --http.api eth,net,txpool,rpc,web3
      --chain /root/ethgen/genesis.json
      --http
      --authrpc.jwtsecret /root/ethgen/jwt.hex
      --http.corsdomain "*"
      --http.port 11545
      --http.addr 192.168.10.17
      --authrpc.port 11551
      --authrpc.addr 192.168.10.17
      --discovery.addr 192.168.10.17
      --discovery.port 60303
      --addr 192.168.10.17
      --port 60303
      --p2p-secret-key /root/ethgen/p2p-secret-3.key
      --bootnodes enode://c58ccefeae4d769d0212d0e9d44aa0a5bc49765d472e758ce16fe9518acb74e576a522a783677ad370f3c3a4991f831a89e0dc02ac18667dd824eb5931d3fca5@192.168.10.11:30303
      --builder.deadline 3
      --builder.max-tasks 24
    volumes: 
      - type: bind
        source: ./ethgen
        target: /root/ethgen
    networks:
      localnet:
        ipv4_address: 192.168.10.17
    ports:
      - "11545:11545"
      - "11551:11551"
      - "60303:60303"

networks:
  localnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24

