name: e2e

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-base:
    strategy:
      matrix:
        docker-type: [base] # Changed docker-version to docker-type for consistency with the Makefile
        os: [polaris-linux-latest]
        go-version: [1.21.5]
        arch: [amd64] # Changed go-arch to arch for consistency with the Makefile
        image-name: ["polard/base:v0.0.0"]
        export-name: [base-image]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image using Makefile
        run: make docker-build DOCKER_TYPE=${{ matrix.docker-type }} ARCH=${{ matrix.arch }} GO_VERSION=${{ matrix.go-version }}
        env:
          GOPATH: /home/runner/go

      - name: Save base image
        run: docker save ${{ matrix.image-name }} -o ${{ matrix.export-name }}.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.export-name }}
          path: ${{ matrix.export-name }}.tar

  build-localnet:
    needs: build-base
    strategy:
      matrix:
        namespace: [cosmos]
        docker-type: [localnet] # Changed docker-version to docker-type for consistency with the Makefile
        os: [polaris-linux-latest]
        go-version: [1.21.5]
        arch: [amd64] # Changed go-arch to arch for consistency with the Makefile
        base-image: [base-image]
        image-name: ["polard/localnet:v0.0.0"]
        export-name: [localnet]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download image artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.base-image }}

      - name: Load image
        run: docker load -i ${{ matrix.base-image }}.tar

      - name: Build Docker Image using Makefile
        run: make docker-build DOCKER_TYPE=${{ matrix.docker-type }} ARCH=${{ matrix.arch }} GO_VERSION=${{ matrix.go-version }}
        env:
          GOPATH: /home/runner/go

      - name: Save base image
        run: docker save ${{ matrix.image-name }} -o ${{ matrix.export-name }}.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.export-name }}
          path: ${{ matrix.export-name }}.tar

  # hive:
  #   needs: build-base
  #   strategy:
  #     matrix:
  #       os: [polaris-linux-latest]
  #       go-version: [1.21.5]
  #       base-image: [base-image]
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Setup Golang
  #       uses: actions/setup-go@v3
  #       with:
  #         go-version: ${{ matrix.go-version }}
  #     - name: Download image artifact
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: ${{ matrix.base-image }}
  #     - name: Load image
  #       run: docker load -i ${{ matrix.base-image }}.tar
  #     - name: Cache Golang Deps
  #       uses: actions/cache@v3
  #       with:
  #         path: |
  #           ~/.cache/go-build
  #           ~/go
  #         key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
  #         restore-keys: |
  #           ${{ runner.os }}-golang-
  #     - name: Run `make test-hive`
  #       run: make hive-setup test-hive
  #       env:
  #         GOPATH: /home/runner/go

  # ci:
  #   needs: build-localnet
  #   strategy:
  #     matrix:
  #       namespace: ["e2e", "localnet"]
  #       os: [polaris-linux-latest]
  #       go-version: [1.21.5]
  #       base-image: [localnet]
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Setup Golang
  #       uses: actions/setup-go@v3
  #       with:
  #         go-version: ${{ matrix.go-version }}
  #     - name: Download image artifact
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: ${{ matrix.base-image }}
  #     - name: Load image
  #       run: docker load -i ${{ matrix.base-image }}.tar
  #     - name: Cache Golang Deps
  #       uses: actions/cache@v3
  #       with:
  #         path: |
  #           ~/.cache/go-build
  #           ~/go
  #         key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
  #         restore-keys: |
  #           ${{ runner.os }}-golang-
  #     - name: Run ${{ matrix.namespace }}
  #       run: make test-${{ matrix.namespace }}
  #       env:
  #         GOPATH: /home/runner/go
